# name: My cowsay workflow

# on: push

# jobs:
#     starter_job:
#         runs-on: ubuntu-latest
#         steps:
#         - name: checkout Repo
#           uses: actions/checkout@v4        

#         - name: Install cowsay
#           run: sudo apt-get update && sudo apt-get install -y cowsay

#         - name: Add cowsay to PATH
#           run: echo "/usr/games" >> $GITHUB_PATH

#         - name: Run cowsay
#           run: |
#             cowsay -f dragon "Just be aware, the lion is still the jungle king" >> lion.txt

#         - name: Test file Exist
#           run: grep -i "lion" lion.txt

#         - name: Display content of lion.txt
#           run: cat lion.txt

#         - name: list and multi-command with cowsaymsge
#           run: |
#             echo "Actions usage with multiple commands"
#             ls -ltra
#             cat README.md


## workflow with shell script.
# name: My cowsay workflow executed with script

# on: push

# jobs:
#   starter_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: List repository files
#         run: ls -ltra

#       - name: Verify ascii-script.sh exists
#         run: |
#           if [ ! -f ./ascii-script.sh ]; then
#             echo "ascii-script.sh not found!" >&2
#             exit 1
#           fi

#       - name: Make ascii-script.sh executable and execute
#         run: |
#           chmod +x ascii-script.sh
#           ./ascii-script.sh


### Multiple jobs in a workflow

name: cowsay workflow multi-jobs

on: push

jobs:
  build_job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Just be aware, the lion is still the jungle king" >> lion.txt

      - name: Sleep for 30 seconds
        run: sleep 30

  test_job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 second
        run: sleep 10

      - name: Test file exists
        run: grep -i "lion" lion.txt

  deploy_job-3:
    runs-on: ubuntu-latest
    steps:
      - name: read File
        run: cat lion.txt

      - name: deploy
        run: echo Deploying files
