# name: Using environment variable at the workflow level

# on:
#     push

# env:
#         CONTAINER_REGISTRY: docker.io
#         DOCKER_USERNAME: manlook01
#         DOCKER_IMAGE: github-actios-nginex

# jobs:
#     docker:
#         runs-on: ubuntu-latest
#         steps:
#             - name: docker Build
#               run: docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest .

#             - name: Docker login
#               env:
#                 DOCKER_PASSWORD: 308VtasYw!
#               run: docker login --username=$DOCKER_USERNAME --password=DOCKER_PASSWORD

#             - name: docker publish
#               run: echo docker $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#     deploy:
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#         - name: Docker Run
#           run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest 

name: Using environment variable at the workflow level

on:
  push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_IMAGE: github-actios-nginex

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:latest .

      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Push
        run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE:latest